---
- name: Get config from lab
  hosts: net-lab
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
  - name: Checking NETCONF
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name:  Fetching configs
    junos_get_config:
      host={{ inventory_hostname }}
      dest=../configs/{{lookup('pipe', 'date -Iseconds')}}-{{ inventory_hostname }}.conf
      format=text
      logfile=../logs/get-config.log
