---
- name: Set interface descriptions based on LLDP
  hosts: net-lab
  roles:
  - Juniper.junos 
  connection: local
  gather_facts: no

  tasks:
  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: GET LLDP
    junos_get_table: table=LLDPNeighborTable file=lldp.yml host={{ inventory_hostname }} 
    register: neighbors

  - name: SET INTERFACE DESCRIPTION
    junos_config:
      host: "{{ inventory_hostname }}"
      replace: true
      lines:
        - set interfaces {{ item['local_int'] }} description "{{ item['remote_sysname'] }} {{ item['remote_port_desc'] }}"
      comment: Changing interface descriptions
    with_items: "{{ neighbors['resource'] }}"
